import { fsChain, link, type TemplateDefinition } from '../flatten.js';

export const aiMl: TemplateDefinition = {
  outline: [
    {
      key: 'init',
      name: 'Initiation',
      children: [
        { key: 'init.kickoff', name: 'Kickoff and problem owner', days: 3 },
        { key: 'init.approved', name: 'Inception approved', isMilestone: true },
      ],
    },
    {
      key: 'frame',
      name: 'Problem framing',
      children: [
        { key: 'frame.decision', name: 'Decision to be supported', days: 5 },
        { key: 'frame.metrics', name: 'Success metrics (precision/recall, error, SLA)', days: 5 },
        { key: 'frame.ethics', name: 'Ethics, bias, and privacy constraints', days: 5 },
        { key: 'frame.signed', name: 'Problem statement signed off', isMilestone: true },
      ],
    },
    {
      key: 'discover',
      name: 'Data discovery',
      children: [
        { key: 'discover.inventory', name: 'Data inventory and access approvals', days: 10 },
        { key: 'discover.quality', name: 'Quality and representativeness review', days: 8 },
        { key: 'discover.labels', name: 'Labeling / ground-truth plan', days: 5 },
        { key: 'discover.access', name: 'Data access granted', isMilestone: true },
      ],
    },
    {
      key: 'design',
      name: 'Design',
      children: [
        { key: 'design.experiment', name: 'Experiment and feature design', days: 8 },
        { key: 'design.inference', name: 'Inference path (batch or API)', days: 5 },
        { key: 'design.mlops', name: 'Environment and MLOps design', days: 5 },
        { key: 'design.approved', name: 'Design approved', isMilestone: true },
      ],
    },
    {
      key: 'infra',
      name: 'Infrastructure setup',
      children: [
        { key: 'infra.dev', name: 'Dev / experiment workspace', days: 8 },
        { key: 'infra.test', name: 'Test / SIT (staging inference)', days: 8 },
        { key: 'infra.prod', name: 'Production inference environment', days: 12 },
        { key: 'infra.access', name: 'Data access, secrets, and isolation', days: 5 },
        { key: 'infra.devtest.ready', name: 'Dev and Test environments ready', isMilestone: true },
      ],
    },
    {
      key: 'mlops',
      name: 'CI/CD & MLOps pipeline',
      children: [
        { key: 'mlops.repo', name: 'Repo (data defs, training, eval, serving)', days: 3 },
        { key: 'mlops.train', name: 'Training / evaluation pipeline', days: 8 },
        { key: 'mlops.registry', name: 'Model registry and promote Dev → Test → Prod', days: 5 },
        { key: 'mlops.gates', name: 'Drift / quality gates', days: 5 },
        { key: 'mlops.live', name: 'MLOps live', isMilestone: true },
      ],
    },
    {
      key: 'data',
      name: 'Data readiness',
      children: [
        { key: 'data.extract', name: 'Extract and secure workspace', days: 8 },
        { key: 'data.clean', name: 'Cleaning and de-identification', days: 10 },
        { key: 'data.label', name: 'Labeling', days: 15 },
        { key: 'data.split', name: 'Train / validation / test split', days: 3 },
        { key: 'data.module', name: 'Data / pipeline module testing', days: 5 },
        { key: 'data.frozen', name: 'Dataset frozen', isMilestone: true },
      ],
    },
    {
      key: 'model',
      name: 'Model development',
      children: [
        { key: 'model.baseline', name: 'Baseline model', days: 8 },
        { key: 'model.iterate', name: 'Feature work and iterations', days: 15 },
        { key: 'model.module', name: 'Model / component module testing', days: 5 },
        { key: 'model.selected', name: 'Candidate model selected', isMilestone: true },
      ],
    },
    {
      key: 'valid',
      name: 'Validation',
      children: [
        { key: 'valid.holdout', name: 'Hold-out evaluation', days: 5 },
        { key: 'valid.bias', name: 'Bias / fairness and error analysis', days: 5 },
        { key: 'valid.explain', name: 'Explainability pack for the department', days: 5 },
        { key: 'valid.accepted', name: 'Model accepted for SIT / pilot', isMilestone: true },
      ],
    },
    {
      key: 'testware',
      name: 'Test planning & cases',
      children: [
        { key: 'testware.plan', name: 'Master test plan (data, model, service)', days: 5 },
        { key: 'testware.sit.cases', name: 'SIT test-case preparation (feature → score → action)', days: 5 },
        { key: 'testware.uat.cases', name: 'UAT test-case preparation (business review of outputs)', days: 5 },
        { key: 'testware.load.prep', name: 'Load-test scenarios (throughput, latency SLA)', days: 3 },
        { key: 'testware.signed', name: 'Testware signed off', isMilestone: true },
      ],
    },
    {
      key: 'sit',
      name: 'SIT, load & security',
      children: [
        { key: 'sit.deploy', name: 'Deploy candidate to Test via MLOps', days: 3 },
        { key: 'sit.exec', name: 'SIT execution (integrated inference path)', days: 8 },
        { key: 'sit.load', name: 'Load / performance testing (inference)', days: 5 },
        { key: 'sit.security', name: 'Security / CERT-In review of the service', days: 8 },
        { key: 'sit.accepted', name: 'SIT accepted', isMilestone: true },
      ],
    },
    {
      key: 'pilot',
      name: 'UAT & pilot',
      children: [
        { key: 'pilot.run', name: 'Limited-user pilot', days: 15 },
        { key: 'pilot.uat', name: 'Human-in-the-loop UAT', days: 10 },
        { key: 'pilot.gng', name: 'Pilot go / no-go', isMilestone: true },
      ],
    },
    {
      key: 'deploy',
      name: 'Deployment (only if go)',
      children: [
        { key: 'deploy.runbook', name: 'Deployment runbook and rollback (model + endpoint)', days: 3 },
        { key: 'deploy.prod', name: 'Production deploy via MLOps', days: 3 },
        { key: 'deploy.smoke', name: 'Prod smoke (golden set)', days: 2 },
        { key: 'deploy.monitor', name: 'Monitoring (drift, latency) live', days: 3 },
        { key: 'deploy.live', name: 'Model in production', isMilestone: true },
      ],
    },
    {
      key: 'close',
      name: 'Closure',
      children: [
        { key: 'close.card', name: 'Model card and runbook', days: 3 },
        { key: 'close.handover', name: 'Handover to O&M', days: 3 },
        { key: 'close.done', name: 'Project closed', isMilestone: true },
      ],
    },
  ],
  links: [
    ...fsChain([
      'init.kickoff',
      'init.approved',
      'frame.decision',
      'frame.metrics',
      'frame.ethics',
      'frame.signed',
    ]),
    ...fsChain(['frame.signed', 'discover.inventory', 'discover.quality', 'discover.labels', 'discover.access']),
    ...fsChain(['discover.access', 'design.experiment', 'design.inference', 'design.mlops', 'design.approved']),
    link('design.approved', 'infra.dev'),
    link('design.approved', 'infra.test'),
    link('design.approved', 'infra.prod'),
    link('infra.dev', 'infra.access'),
    link('infra.test', 'infra.access'),
    link('infra.access', 'infra.devtest.ready'),
    ...fsChain(['infra.devtest.ready', 'mlops.repo', 'mlops.train', 'mlops.registry', 'mlops.gates', 'mlops.live']),
    ...fsChain(['mlops.live', 'data.extract', 'data.clean', 'data.label', 'data.split', 'data.module', 'data.frozen']),
    ...fsChain(['data.frozen', 'model.baseline', 'model.iterate', 'model.module', 'model.selected']),
    ...fsChain(['model.selected', 'valid.holdout', 'valid.bias', 'valid.explain', 'valid.accepted']),
    link('frame.signed', 'testware.plan', 'SS'),
    link('design.approved', 'testware.sit.cases', 'SS'),
    link('design.approved', 'testware.uat.cases', 'SS'),
    link('testware.plan', 'testware.load.prep'),
    link('testware.sit.cases', 'testware.signed'),
    link('testware.uat.cases', 'testware.signed'),
    link('testware.load.prep', 'testware.signed'),
    link('valid.accepted', 'sit.deploy'),
    link('testware.signed', 'sit.deploy'),
    ...fsChain(['sit.deploy', 'sit.exec', 'sit.load', 'sit.security', 'sit.accepted']),
    ...fsChain(['sit.accepted', 'pilot.run', 'pilot.uat', 'pilot.gng']),
    link('pilot.gng', 'deploy.runbook'),
    link('infra.prod', 'deploy.runbook'),
    ...fsChain(['deploy.runbook', 'deploy.prod', 'deploy.smoke', 'deploy.monitor', 'deploy.live']),
    ...fsChain(['deploy.live', 'close.card', 'close.handover', 'close.done']),
  ],
};
