import { fsChain, link, type TemplateDefinition } from '../flatten.js';

export const appDevelopment: TemplateDefinition = {
  outline: [
    {
      key: 'init',
      name: 'Initiation & governance',
      children: [
        { key: 'init.kickoff', name: 'Kickoff and team mobilization', days: 3 },
        { key: 'init.report', name: 'Inception / kickoff report', days: 5 },
        { key: 'init.governance', name: 'Steering committee and PMC setup', days: 3 },
        { key: 'init.approved', name: 'Inception approved', isMilestone: true },
      ],
    },
    {
      key: 'req',
      name: 'Requirements',
      children: [
        { key: 'req.asis', name: 'As-Is process study', days: 10 },
        { key: 'req.workshops', name: 'Stakeholder workshops', days: 10 },
        { key: 'req.frs', name: 'FRS', days: 10 },
        { key: 'req.srs', name: 'SRS', days: 10 },
        { key: 'req.walkthrough', name: 'Requirements walkthrough', days: 5 },
        { key: 'req.signed', name: 'SRS signed off', isMilestone: true },
      ],
    },
    {
      key: 'design',
      name: 'Design',
      children: [
        { key: 'design.hld', name: 'Solution architecture (HLD)', days: 10 },
        { key: 'design.lld', name: 'Module / LLD', days: 10 },
        { key: 'design.ux', name: 'UI/UX wireframes', days: 10 },
        { key: 'design.security', name: 'Security design (MeitY / CERT-In baseline)', days: 5 },
        { key: 'design.integration', name: 'Integration design', days: 5 },
        { key: 'design.env', name: 'Environment and deployment design (Dev / Test / Prod)', days: 5 },
        { key: 'design.approved', name: 'Design approved', isMilestone: true },
      ],
    },
    {
      key: 'infra',
      name: 'Infrastructure setup',
      children: [
        { key: 'infra.dev', name: 'Dev environment', days: 10 },
        { key: 'infra.test', name: 'Test / SIT environment', days: 10 },
        { key: 'infra.prod', name: 'Production environment', days: 15 },
        { key: 'infra.access', name: 'Network, access, and secrets', days: 5 },
        { key: 'infra.devtest.ready', name: 'Dev and Test environments ready', isMilestone: true },
      ],
    },
    {
      key: 'cicd',
      name: 'CI/CD pipeline',
      children: [
        { key: 'cicd.repo', name: 'Source control and branching', days: 3 },
        { key: 'cicd.build', name: 'Build and unit-test pipeline', days: 5 },
        { key: 'cicd.deploy', name: 'Deploy pipeline (Dev → Test → Prod)', days: 5 },
        { key: 'cicd.gates', name: 'Quality gates (lint, SAST, artefact scan)', days: 5 },
        { key: 'cicd.live', name: 'CI/CD live', isMilestone: true },
      ],
    },
    {
      key: 'build',
      name: 'Build',
      children: [
        { key: 'build.modules', name: 'Module development', days: 40 },
        { key: 'build.unit', name: 'Unit testing', days: 10 },
        { key: 'build.module', name: 'Module testing', days: 10 },
        { key: 'build.integration', name: 'Integration testing (dev)', days: 10 },
        { key: 'build.done', name: 'Development complete', isMilestone: true },
      ],
    },
    {
      key: 'testware',
      name: 'Test planning & cases',
      children: [
        { key: 'testware.plan', name: 'Master test plan', days: 5 },
        { key: 'testware.sit.cases', name: 'SIT test-case preparation', days: 10 },
        { key: 'testware.uat.cases', name: 'UAT test-case preparation', days: 10 },
        { key: 'testware.load.prep', name: 'Load-test scenario and data preparation', days: 5 },
        { key: 'testware.signed', name: 'Testware signed off', isMilestone: true },
      ],
    },
    {
      key: 'sit',
      name: 'SIT, load & security',
      children: [
        { key: 'sit.exec', name: 'SIT execution', days: 15 },
        { key: 'sit.defects', name: 'SIT defect closure', days: 10 },
        { key: 'sit.load', name: 'Load / performance testing', days: 10 },
        { key: 'sit.vapt', name: 'VAPT', days: 10 },
        { key: 'sit.stqc', name: 'STQC / security audit', days: 15 },
        { key: 'sit.closure', name: 'Defect closure (perf / security)', days: 10 },
        { key: 'sit.clearance', name: 'SIT and security clearance', isMilestone: true },
      ],
    },
    {
      key: 'uat',
      name: 'UAT & pilot',
      children: [
        { key: 'uat.refresh', name: 'UAT environment refresh from Test', days: 3 },
        { key: 'uat.exec', name: 'UAT execution', days: 15 },
        { key: 'uat.pilot', name: 'Limited pilot (office / district)', days: 10 },
        { key: 'uat.accepted', name: 'UAT accepted', isMilestone: true },
      ],
    },
    {
      key: 'deploy',
      name: 'Deployment',
      children: [
        { key: 'deploy.runbook', name: 'Deployment runbook and rollback', days: 5 },
        { key: 'deploy.checklist', name: 'Production readiness checklist', days: 3 },
        { key: 'deploy.prod', name: 'Production deployment (via CI/CD)', days: 3 },
        { key: 'deploy.smoke', name: 'Smoke test on Prod', days: 2 },
        { key: 'deploy.golive', name: 'Go-live', isMilestone: true },
      ],
    },
    {
      key: 'train',
      name: 'Training & change management',
      children: [
        { key: 'train.material', name: 'Training material', days: 5 },
        { key: 'train.admin', name: 'Admin training', days: 5 },
        { key: 'train.users', name: 'End-user training', days: 5 },
        { key: 'train.done', name: 'Training complete', isMilestone: true },
      ],
    },
    {
      key: 'close',
      name: 'Closure',
      children: [
        { key: 'close.docs', name: 'Documentation and knowledge transfer', days: 5 },
        { key: 'close.handover', name: 'Handover to O&M', days: 5 },
        { key: 'close.done', name: 'Project closed', isMilestone: true },
      ],
    },
  ],
  links: [
    ...fsChain(['init.kickoff', 'init.report', 'init.governance', 'init.approved']),
    ...fsChain(['init.approved', 'req.asis', 'req.workshops', 'req.frs', 'req.srs', 'req.walkthrough', 'req.signed']),
    ...fsChain([
      'req.signed',
      'design.hld',
      'design.lld',
      'design.ux',
      'design.security',
      'design.integration',
      'design.env',
      'design.approved',
    ]),
    link('design.approved', 'infra.dev'),
    link('design.approved', 'infra.test'),
    link('design.approved', 'infra.prod'),
    link('infra.dev', 'infra.access'),
    link('infra.test', 'infra.access'),
    link('infra.access', 'infra.devtest.ready'),
    ...fsChain(['infra.devtest.ready', 'cicd.repo', 'cicd.build', 'cicd.deploy', 'cicd.gates', 'cicd.live']),
    ...fsChain(['cicd.live', 'build.modules', 'build.unit', 'build.module', 'build.integration', 'build.done']),
    link('req.signed', 'testware.plan', 'SS'),
    link('design.approved', 'testware.sit.cases', 'SS'),
    link('design.approved', 'testware.uat.cases', 'SS'),
    link('testware.plan', 'testware.load.prep'),
    link('testware.sit.cases', 'testware.signed'),
    link('testware.uat.cases', 'testware.signed'),
    link('testware.load.prep', 'testware.signed'),
    link('build.done', 'sit.exec'),
    link('testware.signed', 'sit.exec'),
    ...fsChain(['sit.exec', 'sit.defects', 'sit.load', 'sit.vapt', 'sit.stqc', 'sit.closure', 'sit.clearance']),
    ...fsChain(['sit.clearance', 'uat.refresh', 'uat.exec', 'uat.pilot', 'uat.accepted']),
    link('uat.accepted', 'deploy.runbook'),
    link('infra.prod', 'deploy.runbook'),
    ...fsChain(['deploy.runbook', 'deploy.checklist', 'deploy.prod', 'deploy.smoke', 'deploy.golive']),
    link('uat.exec', 'train.material', 'SS'),
    ...fsChain(['train.material', 'train.admin', 'train.users', 'train.done']),
    link('deploy.golive', 'close.docs'),
    link('train.done', 'close.docs'),
    ...fsChain(['close.docs', 'close.handover', 'close.done']),
  ],
};
