import { fsChain, link, type TemplateDefinition } from '../flatten.js';

export const applicationMigration: TemplateDefinition = {
  outline: [
    {
      key: 'init',
      name: 'Initiation',
      children: [
        { key: 'init.kickoff', name: 'Kickoff and vendor / department roles', days: 3 },
        { key: 'init.approved', name: 'Inception approved', isMilestone: true },
      ],
    },
    {
      key: 'disc',
      name: 'Discovery',
      children: [
        { key: 'disc.inventory', name: 'Application and interface inventory', days: 10 },
        { key: 'disc.baseline', name: 'User, role, and volume baseline', days: 8 },
        { key: 'disc.debt', name: 'Technical debt and constraint log', days: 5 },
        { key: 'disc.done', name: 'Discovery complete', isMilestone: true },
      ],
    },
    {
      key: 'strategy',
      name: 'Target architecture & strategy',
      children: [
        { key: 'strategy.hld', name: 'Target HLD (rehost / replatform / rewrite)', days: 10 },
        { key: 'strategy.waves', name: 'Wave / module migration plan', days: 8 },
        { key: 'strategy.parallel', name: 'Rollback and parallel-run design', days: 5 },
        { key: 'strategy.env', name: 'Target environment and cutover design', days: 5 },
        { key: 'strategy.approved', name: 'Strategy approved', isMilestone: true },
      ],
    },
    {
      key: 'infra',
      name: 'Infrastructure setup (target)',
      children: [
        { key: 'infra.dev', name: 'Target Dev', days: 10 },
        { key: 'infra.test', name: 'Target Test / SIT', days: 10 },
        { key: 'infra.prod', name: 'Target Production', days: 15 },
        { key: 'infra.connect', name: 'Connectivity to legacy and downstream systems', days: 8 },
        { key: 'infra.devtest.ready', name: 'Target Dev and Test ready', isMilestone: true },
      ],
    },
    {
      key: 'cicd',
      name: 'CI/CD pipeline (target)',
      children: [
        { key: 'cicd.repo', name: 'Repo and branching for ported code', days: 3 },
        { key: 'cicd.build', name: 'Build / test pipeline', days: 5 },
        { key: 'cicd.promote', name: 'Promote Dev → Test → Prod', days: 5 },
        { key: 'cicd.live', name: 'CI/CD live', isMilestone: true },
      ],
    },
    {
      key: 'build',
      name: 'Build / port',
      children: [
        { key: 'build.port', name: 'Application port or rewrite', days: 40 },
        { key: 'build.interfaces', name: 'Interface rebuild', days: 15 },
        { key: 'build.unit', name: 'Unit testing', days: 10 },
        { key: 'build.module', name: 'Module testing (ported modules vs legacy behaviour)', days: 10 },
        { key: 'build.done', name: 'Target application ready', isMilestone: true },
      ],
    },
    {
      key: 'data',
      name: 'Data workstream (in-project)',
      children: [
        { key: 'data.map', name: 'Critical-data mapping', days: 10 },
        { key: 'data.trial', name: 'Trial migration', days: 10 },
        { key: 'data.accepted', name: 'Trial data accepted', isMilestone: true },
      ],
    },
    {
      key: 'testware',
      name: 'Test planning & cases',
      children: [
        { key: 'testware.plan', name: 'Master test plan (regression vs legacy)', days: 5 },
        { key: 'testware.sit.cases', name: 'SIT test-case preparation (parity + interfaces)', days: 10 },
        { key: 'testware.uat.cases', name: 'UAT test-case preparation (department processes)', days: 8 },
        { key: 'testware.load.prep', name: 'Load-test scenarios (legacy peak volumes)', days: 5 },
        { key: 'testware.signed', name: 'Testware signed off', isMilestone: true },
      ],
    },
    {
      key: 'sit',
      name: 'SIT, load & security',
      children: [
        { key: 'sit.exec', name: 'SIT execution (target + interfaces)', days: 15 },
        { key: 'sit.regression', name: 'Regression vs legacy', days: 10 },
        { key: 'sit.load', name: 'Load / performance vs baseline', days: 8 },
        { key: 'sit.security', name: 'VAPT / STQC on target', days: 15 },
        { key: 'sit.defects', name: 'Defect closure', days: 10 },
        { key: 'sit.clearance', name: 'Target cleared', isMilestone: true },
      ],
    },
    {
      key: 'uat',
      name: 'UAT',
      children: [
        { key: 'uat.refresh', name: 'UAT environment refresh', days: 3 },
        { key: 'uat.exec', name: 'UAT execution', days: 15 },
        { key: 'uat.accepted', name: 'UAT accepted', isMilestone: true },
      ],
    },
    {
      key: 'parallel',
      name: 'Parallel run',
      children: [
        { key: 'parallel.setup', name: 'Dual-run setup', days: 5 },
        { key: 'parallel.run', name: 'Parallel run (period)', days: 20 },
        { key: 'parallel.variance', name: 'Variance closure', days: 8 },
        { key: 'parallel.accepted', name: 'Parallel run accepted', isMilestone: true },
      ],
    },
    {
      key: 'cutover',
      name: 'Deployment & cutover',
      children: [
        { key: 'cutover.runbook', name: 'Deployment runbook and rollback', days: 5 },
        { key: 'cutover.rehearsal', name: 'Cutover rehearsal (deploy + smoke)', days: 5 },
        { key: 'cutover.deploy', name: 'Production deployment via CI/CD', days: 3 },
        { key: 'cutover.window', name: 'Cutover window', days: 3 },
        { key: 'cutover.smoke', name: 'Prod smoke and hypercare start', days: 5 },
        { key: 'cutover.done', name: 'Cutover complete', isMilestone: true },
      ],
    },
    {
      key: 'close',
      name: 'Decommission & closure',
      children: [
        { key: 'close.legacy', name: 'Legacy freeze / archive', days: 5 },
        { key: 'close.train', name: 'Training and KT', days: 8 },
        { key: 'close.handover', name: 'Handover to O&M', days: 5 },
        { key: 'close.done', name: 'Project closed', isMilestone: true },
      ],
    },
  ],
  links: [
    ...fsChain(['init.kickoff', 'init.approved', 'disc.inventory', 'disc.baseline', 'disc.debt', 'disc.done']),
    ...fsChain([
      'disc.done',
      'strategy.hld',
      'strategy.waves',
      'strategy.parallel',
      'strategy.env',
      'strategy.approved',
    ]),
    link('strategy.approved', 'infra.dev'),
    link('strategy.approved', 'infra.test'),
    link('strategy.approved', 'infra.prod'),
    link('infra.dev', 'infra.connect'),
    link('infra.test', 'infra.connect'),
    link('infra.connect', 'infra.devtest.ready'),
    ...fsChain(['infra.devtest.ready', 'cicd.repo', 'cicd.build', 'cicd.promote', 'cicd.live']),
    ...fsChain(['cicd.live', 'build.port', 'build.interfaces', 'build.unit', 'build.module', 'build.done']),
    link('cicd.live', 'data.map'),
    ...fsChain(['data.map', 'data.trial', 'data.accepted']),
    link('strategy.approved', 'testware.plan', 'SS'),
    link('strategy.approved', 'testware.sit.cases', 'SS'),
    link('strategy.approved', 'testware.uat.cases', 'SS'),
    link('testware.plan', 'testware.load.prep'),
    link('testware.sit.cases', 'testware.signed'),
    link('testware.uat.cases', 'testware.signed'),
    link('testware.load.prep', 'testware.signed'),
    link('build.done', 'sit.exec'),
    link('data.accepted', 'sit.exec'),
    link('testware.signed', 'sit.exec'),
    ...fsChain(['sit.exec', 'sit.regression', 'sit.load', 'sit.security', 'sit.defects', 'sit.clearance']),
    ...fsChain(['sit.clearance', 'uat.refresh', 'uat.exec', 'uat.accepted']),
    ...fsChain(['uat.accepted', 'parallel.setup', 'parallel.run', 'parallel.variance', 'parallel.accepted']),
    link('parallel.accepted', 'cutover.runbook'),
    link('infra.prod', 'cutover.runbook'),
    ...fsChain([
      'cutover.runbook',
      'cutover.rehearsal',
      'cutover.deploy',
      'cutover.window',
      'cutover.smoke',
      'cutover.done',
    ]),
    ...fsChain(['cutover.done', 'close.legacy', 'close.train', 'close.handover', 'close.done']),
  ],
};
