import { fsChain, link, type TemplateDefinition } from '../flatten.js';

export const cotsImplementation: TemplateDefinition = {
  outline: [
    {
      key: 'init',
      name: 'Initiation',
      children: [
        { key: 'init.kickoff', name: 'Kickoff, licenses, and ATS confirmation', days: 3 },
        { key: 'init.sandbox', name: 'Product instance / sandbox access', days: 5 },
        { key: 'init.approved', name: 'Inception approved', isMilestone: true },
      ],
    },
    {
      key: 'fit',
      name: 'Fit-gap',
      children: [
        { key: 'fit.workshops', name: 'Process workshops vs product', days: 10 },
        { key: 'fit.register', name: 'Fit-gap register (fit / config / customize / workaround)', days: 8 },
        { key: 'fit.signed', name: 'Fit-gap signed off', isMilestone: true },
      ],
    },
    {
      key: 'design',
      name: 'Solution design',
      children: [
        { key: 'design.process', name: 'To-Be process and org roles', days: 8 },
        { key: 'design.config', name: 'Configuration design', days: 8 },
        { key: 'design.ricefw', name: 'RICEFW / customization list (keep thin)', days: 5 },
        { key: 'design.integration', name: 'Integration design', days: 8 },
        { key: 'design.topology', name: 'Instance topology (Dev / Test / Prod) and transport path', days: 5 },
        { key: 'design.approved', name: 'Design approved', isMilestone: true },
      ],
    },
    {
      key: 'infra',
      name: 'Infrastructure setup',
      children: [
        { key: 'infra.dev', name: 'Dev / sandbox instance', days: 8 },
        { key: 'infra.test', name: 'Test / SIT instance', days: 8 },
        { key: 'infra.prod', name: 'Production instance', days: 12 },
        { key: 'infra.landing', name: 'Integrations landing (IDP, interfaces, printers, mail)', days: 8 },
        { key: 'infra.devtest.ready', name: 'Dev and Test instances ready', isMilestone: true },
      ],
    },
    {
      key: 'cicd',
      name: 'CI/CD / transport path',
      children: [
        { key: 'cicd.repo', name: 'Config and RICEFW repository', days: 3 },
        { key: 'cicd.promote', name: 'Transport / promotion Dev → Test → Prod', days: 5 },
        { key: 'cicd.checks', name: 'Automated checks (where the product allows)', days: 5 },
        { key: 'cicd.live', name: 'Promotion path live', isMilestone: true },
      ],
    },
    {
      key: 'build',
      name: 'Build (configure)',
      children: [
        { key: 'build.config', name: 'Core configuration', days: 20 },
        { key: 'build.master', name: 'Master data templates and load', days: 10 },
        { key: 'build.integrations', name: 'Integrations', days: 15 },
        { key: 'build.roles', name: 'Roles, SoD, and audit trails', days: 8 },
        { key: 'build.custom', name: 'Limited customizations (if any)', days: 15 },
        { key: 'build.module', name: 'Module testing (process / config unit tests)', days: 8 },
        { key: 'build.done', name: 'Build complete', isMilestone: true },
      ],
    },
    {
      key: 'testware',
      name: 'Test planning & cases',
      children: [
        { key: 'testware.plan', name: 'Master test plan (CRP, SIT, UAT, load)', days: 5 },
        { key: 'testware.sit.cases', name: 'SIT test-case preparation (E2E + interfaces)', days: 10 },
        { key: 'testware.uat.cases', name: 'UAT test-case preparation (department processes)', days: 8 },
        { key: 'testware.load.prep', name: 'Load-test scenarios (concurrent users, batch windows)', days: 5 },
        { key: 'testware.signed', name: 'Testware signed off', isMilestone: true },
      ],
    },
    {
      key: 'sit',
      name: 'SIT, load & security',
      children: [
        { key: 'sit.promote', name: 'Promote build to Test', days: 2 },
        { key: 'sit.crp', name: 'Conference-room pilot / SIT', days: 15 },
        { key: 'sit.load', name: 'Load / performance testing', days: 8 },
        { key: 'sit.vapt', name: 'VAPT on exposed surfaces', days: 8 },
        { key: 'sit.defects', name: 'Defect closure', days: 10 },
        { key: 'sit.done', name: 'SIT complete', isMilestone: true },
      ],
    },
    {
      key: 'uat',
      name: 'UAT & training',
      children: [
        { key: 'uat.refresh', name: 'UAT instance refresh', days: 3 },
        { key: 'uat.exec', name: 'UAT execution', days: 15 },
        { key: 'uat.train', name: 'Role-based training', days: 8 },
        { key: 'uat.accepted', name: 'UAT accepted', isMilestone: true },
      ],
    },
    {
      key: 'deploy',
      name: 'Deployment',
      children: [
        { key: 'deploy.runbook', name: 'Deployment / cutover runbook and rollback', days: 5 },
        { key: 'deploy.transport', name: 'Production transport via promotion path', days: 3 },
        { key: 'deploy.master', name: 'Master-data cutover', days: 3 },
        { key: 'deploy.smoke', name: 'Prod smoke', days: 2 },
        { key: 'deploy.golive', name: 'Go-live', isMilestone: true },
      ],
    },
    {
      key: 'close',
      name: 'Hypercare & closure',
      children: [
        { key: 'close.hypercare', name: 'Hypercare (2–4 weeks)', days: 15 },
        { key: 'close.handover', name: 'Handover to O&M / ATS', days: 5 },
        { key: 'close.done', name: 'Project closed', isMilestone: true },
      ],
    },
  ],
  links: [
    ...fsChain(['init.kickoff', 'init.sandbox', 'init.approved', 'fit.workshops', 'fit.register', 'fit.signed']),
    ...fsChain([
      'fit.signed',
      'design.process',
      'design.config',
      'design.ricefw',
      'design.integration',
      'design.topology',
      'design.approved',
    ]),
    link('design.approved', 'infra.dev'),
    link('design.approved', 'infra.test'),
    link('design.approved', 'infra.prod'),
    link('infra.dev', 'infra.landing'),
    link('infra.test', 'infra.landing'),
    link('infra.landing', 'infra.devtest.ready'),
    ...fsChain(['infra.devtest.ready', 'cicd.repo', 'cicd.promote', 'cicd.checks', 'cicd.live']),
    link('cicd.live', 'build.config'),
    link('build.config', 'build.master'),
    link('build.config', 'build.integrations'),
    link('build.config', 'build.roles'),
    link('build.config', 'build.custom'),
    link('build.master', 'build.module'),
    link('build.integrations', 'build.module'),
    link('build.roles', 'build.module'),
    link('build.custom', 'build.module'),
    link('build.module', 'build.done'),
    link('fit.signed', 'testware.plan', 'SS'),
    link('design.approved', 'testware.sit.cases', 'SS'),
    link('design.approved', 'testware.uat.cases', 'SS'),
    link('testware.plan', 'testware.load.prep'),
    link('testware.sit.cases', 'testware.signed'),
    link('testware.uat.cases', 'testware.signed'),
    link('testware.load.prep', 'testware.signed'),
    link('build.done', 'sit.promote'),
    link('testware.signed', 'sit.promote'),
    ...fsChain(['sit.promote', 'sit.crp', 'sit.load', 'sit.vapt', 'sit.defects', 'sit.done']),
    ...fsChain(['sit.done', 'uat.refresh', 'uat.exec']),
    link('uat.exec', 'uat.train', 'SS'),
    link('uat.exec', 'uat.accepted'),
    link('uat.train', 'uat.accepted'),
    link('uat.accepted', 'deploy.runbook'),
    link('infra.prod', 'deploy.runbook'),
    ...fsChain(['deploy.runbook', 'deploy.transport', 'deploy.master', 'deploy.smoke', 'deploy.golive']),
    ...fsChain(['deploy.golive', 'close.hypercare', 'close.handover', 'close.done']),
  ],
};
