import { fsChain, link, type TemplateDefinition } from '../flatten.js';

export const dashboardingMis: TemplateDefinition = {
  outline: [
    {
      key: 'init',
      name: 'Initiation',
      children: [
        { key: 'init.kickoff', name: 'Kickoff and sponsor alignment', days: 3 },
        { key: 'init.audience', name: 'Audience and decision-use definition', days: 5 },
        { key: 'init.approved', name: 'Inception approved', isMilestone: true },
      ],
    },
    {
      key: 'kpi',
      name: 'KPI & indicator catalog',
      children: [
        { key: 'kpi.list', name: 'Scheme / outcome indicator list', days: 8 },
        { key: 'kpi.formula', name: 'Formula, grain, and frequency', days: 5 },
        { key: 'kpi.steward', name: 'Owner and data steward per KPI', days: 3 },
        { key: 'kpi.signed', name: 'KPI catalog signed off', isMilestone: true },
      ],
    },
    {
      key: 'source',
      name: 'Data-source assessment',
      children: [
        { key: 'source.inventory', name: 'Source system inventory', days: 8 },
        { key: 'source.quality', name: 'Access, quality, and latency check', days: 8 },
        { key: 'source.gaps', name: 'Gap list (missing / delayed sources)', days: 5 },
        { key: 'source.ready', name: 'Source readiness noted', isMilestone: true },
      ],
    },
    {
      key: 'design',
      name: 'Design',
      children: [
        { key: 'design.map', name: 'Information architecture / dashboard map', days: 8 },
        { key: 'design.wire', name: 'Wireframes (CM / secretary / operational views)', days: 8 },
        { key: 'design.semantic', name: 'Semantic / star-schema design', days: 8 },
        { key: 'design.env', name: 'Environment and refresh-architecture design', days: 5 },
        { key: 'design.approved', name: 'Design approved', isMilestone: true },
      ],
    },
    {
      key: 'infra',
      name: 'Infrastructure setup',
      children: [
        { key: 'infra.dev', name: 'Dev workspace (BI + pipeline)', days: 8 },
        { key: 'infra.test', name: 'Test / SIT workspace', days: 8 },
        { key: 'infra.prod', name: 'Production workspace', days: 10 },
        { key: 'infra.access', name: 'Source connectivity and secrets', days: 5 },
        { key: 'infra.devtest.ready', name: 'Dev and Test workspaces ready', isMilestone: true },
      ],
    },
    {
      key: 'cicd',
      name: 'CI/CD pipeline',
      children: [
        { key: 'cicd.repo', name: 'Repo for semantic models, ETL, and report defs', days: 3 },
        { key: 'cicd.test', name: 'Pipeline test job (transform + KPI checks)', days: 5 },
        { key: 'cicd.promote', name: 'Promote Dev → Test → Prod', days: 5 },
        { key: 'cicd.live', name: 'CI/CD live', isMilestone: true },
      ],
    },
    {
      key: 'pipe',
      name: 'Data pipeline',
      children: [
        { key: 'pipe.extract', name: 'Extract and staging', days: 10 },
        { key: 'pipe.mart', name: 'Transform and KPI mart', days: 15 },
        { key: 'pipe.refresh', name: 'Incremental refresh', days: 8 },
        { key: 'pipe.module', name: 'Pipeline / module testing (job-level)', days: 8 },
        { key: 'pipe.done', name: 'Pipeline complete', isMilestone: true },
      ],
    },
    {
      key: 'dash',
      name: 'Dashboard build',
      children: [
        { key: 'dash.lead', name: 'Leadership dashboards', days: 12 },
        { key: 'dash.ops', name: 'Operational / drill-through views', days: 10 },
        { key: 'dash.rbac', name: 'Role-based access', days: 5 },
        { key: 'dash.module', name: 'Report / visual module testing', days: 5 },
        { key: 'dash.done', name: 'Dashboards complete', isMilestone: true },
      ],
    },
    {
      key: 'testware',
      name: 'Test planning & cases',
      children: [
        { key: 'testware.plan', name: 'Master test plan (reconciliation + UX + refresh SLA)', days: 5 },
        { key: 'testware.sit.cases', name: 'SIT test-case preparation (source → mart → visual)', days: 8 },
        { key: 'testware.uat.cases', name: 'UAT test-case preparation (decision-maker scripts)', days: 5 },
        { key: 'testware.load.prep', name: 'Load-test scenarios (concurrent viewers, refresh window)', days: 5 },
        { key: 'testware.signed', name: 'Testware signed off', isMilestone: true },
      ],
    },
    {
      key: 'sit',
      name: 'SIT, load & validation',
      children: [
        { key: 'sit.exec', name: 'SIT execution (end-to-end lineage)', days: 10 },
        { key: 'sit.recon', name: 'Number reconciliation vs source', days: 8 },
        { key: 'sit.load', name: 'Load / concurrency testing', days: 5 },
        { key: 'sit.defects', name: 'Defect closure', days: 8 },
        { key: 'sit.accepted', name: 'SIT accepted', isMilestone: true },
      ],
    },
    {
      key: 'uat',
      name: 'UAT',
      children: [
        { key: 'uat.refresh', name: 'Test workspace refresh', days: 2 },
        { key: 'uat.exec', name: 'Department UAT', days: 10 },
        { key: 'uat.accepted', name: 'UAT accepted', isMilestone: true },
      ],
    },
    {
      key: 'deploy',
      name: 'Deployment',
      children: [
        { key: 'deploy.runbook', name: 'Deployment runbook and rollback (dataset + reports)', days: 3 },
        { key: 'deploy.publish', name: 'Production publish via CI/CD', days: 3 },
        { key: 'deploy.sla', name: 'Refresh SLA and alert setup', days: 3 },
        { key: 'deploy.smoke', name: 'Prod smoke (KPI spot-checks)', days: 2 },
        { key: 'deploy.golive', name: 'Go-live', isMilestone: true },
      ],
    },
    {
      key: 'close',
      name: 'Training & closure',
      children: [
        { key: 'close.train', name: 'Admin / analyst training', days: 5 },
        { key: 'close.handover', name: 'Handover to O&M', days: 3 },
        { key: 'close.done', name: 'Project closed', isMilestone: true },
      ],
    },
  ],
  links: [
    ...fsChain(['init.kickoff', 'init.audience', 'init.approved']),
    ...fsChain(['init.approved', 'kpi.list', 'kpi.formula', 'kpi.steward', 'kpi.signed']),
    ...fsChain(['kpi.signed', 'source.inventory', 'source.quality', 'source.gaps', 'source.ready']),
    ...fsChain(['source.ready', 'design.map', 'design.wire', 'design.semantic', 'design.env', 'design.approved']),
    link('design.approved', 'infra.dev'),
    link('design.approved', 'infra.test'),
    link('design.approved', 'infra.prod'),
    link('infra.dev', 'infra.access'),
    link('infra.test', 'infra.access'),
    link('infra.access', 'infra.devtest.ready'),
    ...fsChain(['infra.devtest.ready', 'cicd.repo', 'cicd.test', 'cicd.promote', 'cicd.live']),
    ...fsChain(['cicd.live', 'pipe.extract', 'pipe.mart', 'pipe.refresh', 'pipe.module', 'pipe.done']),
    link('pipe.mart', 'dash.lead', 'SS'),
    ...fsChain(['dash.lead', 'dash.ops', 'dash.rbac', 'dash.module', 'dash.done']),
    link('kpi.signed', 'testware.plan', 'SS'),
    link('design.approved', 'testware.sit.cases', 'SS'),
    link('design.approved', 'testware.uat.cases', 'SS'),
    link('testware.plan', 'testware.load.prep'),
    link('testware.sit.cases', 'testware.signed'),
    link('testware.uat.cases', 'testware.signed'),
    link('testware.load.prep', 'testware.signed'),
    link('pipe.done', 'sit.exec'),
    link('dash.done', 'sit.exec'),
    link('testware.signed', 'sit.exec'),
    ...fsChain(['sit.exec', 'sit.recon', 'sit.load', 'sit.defects', 'sit.accepted']),
    ...fsChain(['sit.accepted', 'uat.refresh', 'uat.exec', 'uat.accepted']),
    link('uat.accepted', 'deploy.runbook'),
    link('infra.prod', 'deploy.runbook'),
    ...fsChain(['deploy.runbook', 'deploy.publish', 'deploy.sla', 'deploy.smoke', 'deploy.golive']),
    ...fsChain(['deploy.golive', 'close.train', 'close.handover', 'close.done']),
  ],
};
