import { fsChain, link, type TemplateDefinition } from '../flatten.js';

export const dataMigration: TemplateDefinition = {
  outline: [
    {
      key: 'init',
      name: 'Initiation',
      children: [
        { key: 'init.kickoff', name: 'Kickoff, scope, and freeze rules', days: 3 },
        { key: 'init.approved', name: 'Inception approved', isMilestone: true },
      ],
    },
    {
      key: 'profile',
      name: 'Source inventory & profiling',
      children: [
        { key: 'profile.inventory', name: 'Source system and table inventory', days: 8 },
        { key: 'profile.profile', name: 'Profiling (nulls, duplicates, orphans)', days: 10 },
        { key: 'profile.volume', name: 'Volume and historical-depth decision', days: 3 },
        { key: 'profile.signed', name: 'Profile signed off', isMilestone: true },
      ],
    },
    {
      key: 'map',
      name: 'Mapping & rules',
      children: [
        { key: 'map.stt', name: 'Source-to-target mapping', days: 15 },
        { key: 'map.transform', name: 'Transformation and default rules', days: 8 },
        { key: 'map.cleanse', name: 'Cleansing and survivorship rules', days: 8 },
        { key: 'map.controls', name: 'Reconciliation control design', days: 5 },
        { key: 'map.signed', name: 'Mapping signed off', isMilestone: true },
      ],
    },
    {
      key: 'infra',
      name: 'Infrastructure setup',
      children: [
        { key: 'infra.dev', name: 'Dev migration workspace', days: 8 },
        { key: 'infra.test', name: 'Test / SIT workspace (trial loads)', days: 8 },
        { key: 'infra.prod', name: 'Production cutover workspace', days: 10 },
        { key: 'infra.connect', name: 'Source / target connectivity and landing zones', days: 5 },
        { key: 'infra.devtest.ready', name: 'Dev and Test workspaces ready', isMilestone: true },
      ],
    },
    {
      key: 'cicd',
      name: 'CI/CD pipeline',
      children: [
        { key: 'cicd.repo', name: 'Repo for jobs, mappings, and control SQL', days: 3 },
        { key: 'cicd.test', name: 'Pipeline (lint, job unit tests, package)', days: 5 },
        { key: 'cicd.promote', name: 'Promote Dev → Test → Prod', days: 5 },
        { key: 'cicd.live', name: 'CI/CD live', isMilestone: true },
      ],
    },
    {
      key: 'kit',
      name: 'Tooling & module testing',
      children: [
        { key: 'kit.jobs', name: 'Scripts / ETL jobs', days: 15 },
        { key: 'kit.controls', name: 'Control totals and exception reports', days: 8 },
        { key: 'kit.module', name: 'Module testing (per domain / subject area)', days: 10 },
        { key: 'kit.ready', name: 'Migration kit ready', isMilestone: true },
      ],
    },
    {
      key: 'testware',
      name: 'Test planning & cases',
      children: [
        { key: 'testware.plan', name: 'Master test plan (trial 1, dress rehearsal, cutover)', days: 5 },
        { key: 'testware.sit.cases', name: 'SIT test-case preparation (row counts, checksums, orphans)', days: 8 },
        { key: 'testware.uat.cases', name: 'UAT test-case preparation (business reconcilers)', days: 5 },
        { key: 'testware.load.prep', name: 'Load-test scenarios (full volume, elapsed window)', days: 5 },
        { key: 'testware.signed', name: 'Testware signed off', isMilestone: true },
      ],
    },
    {
      key: 'trial1',
      name: 'SIT — trial load 1',
      children: [
        { key: 'trial1.deploy', name: 'Deploy kit to Test via CI/CD', days: 2 },
        { key: 'trial1.load', name: 'Extract and load (agreed scope)', days: 8 },
        { key: 'trial1.sit', name: 'SIT execution / reconciliation 1', days: 8 },
        { key: 'trial1.fixes', name: 'Defect and rule fixes', days: 8 },
        { key: 'trial1.accepted', name: 'Trial 1 accepted', isMilestone: true },
      ],
    },
    {
      key: 'rehearsal',
      name: 'Load testing & dress rehearsal',
      children: [
        { key: 'rehearsal.load', name: 'Full-volume load test', days: 5 },
        { key: 'rehearsal.trial2', name: 'Trial load 2 (dress rehearsal)', days: 8 },
        { key: 'rehearsal.recon', name: 'Reconciliation 2', days: 5 },
        { key: 'rehearsal.runbook', name: 'Cutover runbook and rollback', days: 3 },
        { key: 'rehearsal.accepted', name: 'Dress rehearsal accepted', isMilestone: true },
      ],
    },
    {
      key: 'uat',
      name: 'UAT',
      children: [
        { key: 'uat.exec', name: 'Business UAT on reconciled Test data', days: 8 },
        { key: 'uat.exceptions', name: 'Exception / suspense sign-off', days: 3 },
        { key: 'uat.accepted', name: 'UAT accepted', isMilestone: true },
      ],
    },
    {
      key: 'cutover',
      name: 'Deployment (cutover)',
      children: [
        { key: 'cutover.deploy', name: 'Deploy approved kit to Prod via CI/CD', days: 2 },
        { key: 'cutover.freeze', name: 'Source freeze / delta extract', days: 2 },
        { key: 'cutover.load', name: 'Production load', days: 3 },
        { key: 'cutover.recon', name: 'Final reconciliation', days: 3 },
        { key: 'cutover.smoke', name: 'Prod smoke (control totals)', days: 1 },
        { key: 'cutover.done', name: 'Data migration complete', isMilestone: true },
      ],
    },
    {
      key: 'close',
      name: 'Closure',
      children: [
        { key: 'close.archive', name: 'Archive mappings and load logs', days: 3 },
        { key: 'close.kt', name: 'KT to app / O&M team', days: 3 },
        { key: 'close.done', name: 'Project closed', isMilestone: true },
      ],
    },
  ],
  links: [
    ...fsChain([
      'init.kickoff',
      'init.approved',
      'profile.inventory',
      'profile.profile',
      'profile.volume',
      'profile.signed',
    ]),
    ...fsChain(['profile.signed', 'map.stt', 'map.transform', 'map.cleanse', 'map.controls', 'map.signed']),
    link('map.signed', 'infra.dev'),
    link('map.signed', 'infra.test'),
    link('map.signed', 'infra.prod'),
    link('infra.dev', 'infra.connect'),
    link('infra.test', 'infra.connect'),
    link('infra.connect', 'infra.devtest.ready'),
    ...fsChain(['infra.devtest.ready', 'cicd.repo', 'cicd.test', 'cicd.promote', 'cicd.live']),
    ...fsChain(['cicd.live', 'kit.jobs', 'kit.controls', 'kit.module', 'kit.ready']),
    link('map.signed', 'testware.plan', 'SS'),
    link('map.signed', 'testware.sit.cases', 'SS'),
    link('map.signed', 'testware.uat.cases', 'SS'),
    link('testware.plan', 'testware.load.prep'),
    link('testware.sit.cases', 'testware.signed'),
    link('testware.uat.cases', 'testware.signed'),
    link('testware.load.prep', 'testware.signed'),
    link('kit.ready', 'trial1.deploy'),
    link('testware.signed', 'trial1.deploy'),
    ...fsChain(['trial1.deploy', 'trial1.load', 'trial1.sit', 'trial1.fixes', 'trial1.accepted']),
    ...fsChain([
      'trial1.accepted',
      'rehearsal.load',
      'rehearsal.trial2',
      'rehearsal.recon',
      'rehearsal.runbook',
      'rehearsal.accepted',
    ]),
    ...fsChain(['rehearsal.accepted', 'uat.exec', 'uat.exceptions', 'uat.accepted']),
    link('uat.accepted', 'cutover.deploy'),
    link('infra.prod', 'cutover.deploy'),
    ...fsChain([
      'cutover.deploy',
      'cutover.freeze',
      'cutover.load',
      'cutover.recon',
      'cutover.smoke',
      'cutover.done',
    ]),
    ...fsChain(['cutover.done', 'close.archive', 'close.kt', 'close.done']),
  ],
};
